### ISSUE TITLE
Setting a particular initial color and I dont get the full range of colors from the slider

### ISSUE THREAD

**Issue by philmetzger** [super-effective/react-color-picker#10]
I have set the initial color as `#1f5257`

```
<ReactColorPicker
      color="#1f5257"
      onChange={onColorChange}
/>
```

Then when I look at the color slider it doesnt feel like its pointing at the right color. Then when I move it around the colors are quite dull.

![image](https://user-images.githubusercontent.com/4325631/104834489-f34ebc80-589f-11eb-9966-9c4ee924ceec.png)

If i select a yellow its not really a yellow and more a gold.
https://codesandbox.io/s/goofy-flower-8gr14?file=/src/App.js

I am guessing maybe because my initial color is not in the color pickers spectrum so to speak? Is there anything I can do?

**Comment by AtomicJon** [comment]
Hey @philmetzger - apologies for the delay in getting back to you on this. It appears that you only have the hue slider visible and not the saturation/value picker. By default, the picker fills its container - the hue slider and bottom controls take a fixed amount of the height and then the saturation/value picker fills the remaining space. In your case the container does not have a fixed height so the saturation/value picker is 0px tall.

To fix this you can either wrap the picker in an element with a defined height, or specify the height style on the picker itself. I have modified your example here demonstrating both approaches here:
https://codesandbox.io/s/vigorous-vaughan-orgsc?file=/src/App.js

**Comment by AtomicJon** [comment]
Closing this for now - let me know if you have any further issues.
